### ISSUE TITLE
Not working in Docker Desktop v4.19.0

### ISSUE THREAD

**Issue by bravoman** [mutagen-io/docker-desktop-extension-issues#7]
After updating to Docker Desktop 4.19 om my M1 Pro Macbook it always gives me this error after going to the Mutagen tab:

![235137539-b61cadf6-8fee-4c74-8fb6-a97e556e537a](https://user-images.githubusercontent.com/1729802/235138327-92adda35-eec5-4ac4-8eb9-e77df5897c1d.png)

**Comment by bravoman** [comment]
After total reinstall of docker and Mutagen from the Extensions Marketplace it doesn't work either. I'm not even able to add any caches anymore. Everything looks fine up until the final "create" in de modal where you choose the GID and UID. After hitting "create" there it doesn't do anything and keeps on showing like this:

![image](https://user-images.githubusercontent.com/1729802/235157271-e9139a43-a27d-42a4-b0d2-fc832bede1c5.png)

**Comment by xenoscopic** [comment]
Hi @bravoman, I'm really sorry about the inconvenience.  I'm investigating at the moment, but I believe something has broken in the extension SDK between 4.18 and 4.19.  I will have a fix published within a few hours.

**Comment by bravoman** [comment]
I've restarting docker engine and restarting docker desktop as whole and nothing seems to work.

**Comment by xenoscopic** [comment]
I think it's something that's going to require a workaround in the code.  Continuing with 4.18 is the only course of action that I can recommend at the moment.  I will notify you as soon as a fix is available.

**Comment by xenoscopic** [comment]
It looks like the cause of the issue is that the `docker` executable is no longer included in the `PATH` of executables launched by the extension SDK.  I'm working on a patch at the moment, I should have it out within an hour.

**Comment by bravoman** [comment]
Cool 👍🏻Op 28 apr. 2023 om 19:18 heeft Jacob Howard ***@***.***> het volgende geschreven:﻿
It looks like the cause of the issue is that the docker executable is no longer included in the PATH of executables launched by the extension SDK.  I'm working on a patch at the moment, I should have it out within an hour.

**Comment by xenoscopic** [comment]
@bravoman @stephpy I've just pushed a new tag (0.17.1).  This should fix the issue.  Docker Desktop may not detect the update for up to 12 hours because of its Marketplace caching, but you can force an update on the command line with:

```
docker extension update mutagenio/docker-desktop-extension:0.17.1
```

Sorry again for the inconvenience, don't hesitate to reach out if you run into any additional issues.

**Comment by LeEnno** [comment]
Thanks for the fix and including instructions to install the update via CLI.
Just gonna leave the error message as plain text here for desperate googlers like me:

> Lost Docker event polling stream

**Comment by xenoscopic** [comment]
@LeEnno Great thinking, I appreciate that.
